-- Migration 085: Real coach emails from official athletic staff pages
-- Generated by scrape_coaches.py
--
-- Updates:
--   1. users.email for each head coach (looked up via coaches.school_name)
--   2. coaches.assistant_staff JSONB with assistant coaches

-- Add assistant_staff column if it doesn't exist
ALTER TABLE coaches ADD COLUMN IF NOT EXISTS
  assistant_staff JSONB NOT NULL DEFAULT '[]'::jsonb;

-- ── University of North Carolina ──────────────────────────────────────────
UPDATE public.users SET email = 'csomoano@uncaa.unc.edu', first_name = 'Carlos', last_name = 'Somoano' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'University of North Carolina' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Carlos Somoano", "title": "Head Coach", "email": "csomoano@uncaa.unc.edu"}, {"name": "Michael Callahan", "title": "Assistant Coach", "email": "mbcallah@unc.edu"}, {"name": "Michael Harrington", "title": "Assistant Coach", "email": "mrharrin@live.unc.edu"}, {"name": "Jeff Negalha", "title": "Assistant Coach", "email": "negalha@unc.edu"}]'::jsonb WHERE school_name = 'University of North Carolina';

-- ── Stanford University ──────────────────────────────────────────
UPDATE public.users SET email = 'smsoccer@stanford.edu', first_name = 'Jeremy', last_name = 'Gunn' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Stanford University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Jeremy Gunn", "title": "Head Coach", "email": "smsoccer@stanford.edu"}, {"name": "Drew Hutchins", "title": "Associate Head Coach", "email": "smsoccer@stanford.edu"}, {"name": "Kevin McCarthy", "title": "Assistant Coach", "email": "smsoccer@stanford.edu"}, {"name": "Woo Jeon", "title": "Assistant Coach", "email": "smsoccer@stanford.edu"}]'::jsonb WHERE school_name = 'Stanford University';

-- ── Indiana University ──────────────────────────────────────────
UPDATE coaches SET assistant_staff = '[{"name": "Christian Lomeli", "title": "Assistant Coach", "email": "clomeli@iu.edu"}, {"name": "Tanner Thompson", "title": "Assistant Coach", "email": "tannthom@iu.edu"}, {"name": "Jacob Bushue", "title": "Assistant Coach", "email": "jbushue@iu.edu"}]'::jsonb WHERE school_name = 'Indiana University';

-- ── Wake Forest University ──────────────────────────────────────────
UPDATE public.users SET email = 'muussrp@wfu.edu', first_name = 'Bobby', last_name = 'Muuss' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Wake Forest University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Bobby Muuss", "title": "Head Coach", "email": "muussrp@wfu.edu"}, {"name": "Dane Brenner", "title": "Associate Head Coach/Director of Recruiting & Player Identification/Director of Goalkeeping", "email": "brennerd@wfu.edu"}, {"name": "Zack Schilawski", "title": "Assistant Coach/Director of Player Development", "email": "schilazj@wfu.edu"}, {"name": "Ade Taiwo", "title": "Assistant Coach/Director of Community Soccer Engagement & Player Welfare", "email": "taiwoa@wfu.edu"}]'::jsonb WHERE school_name = 'Wake Forest University';

-- ── Georgetown University ──────────────────────────────────────────
UPDATE public.users SET email = 'gumenssoccer@georgetown.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Georgetown University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Coach", "title": "202-687-2364202-687-2364", "email": "gumenssoccer@georgetown.edu"}, {"name": "Assistant Coach", "title": "TBATBA", "email": "mm5289@georgetown.edu"}]'::jsonb WHERE school_name = 'Georgetown University';

-- ── Clemson University ──────────────────────────────────────────
UPDATE coaches SET assistant_staff = '[{"name": "Phil Jones", "title": "Associate Head Coach", "email": "msoccer@clemson.edu"}]'::jsonb WHERE school_name = 'Clemson University';

-- ── University of Virginia ──────────────────────────────────────────
UPDATE public.users SET email = 'Vrp9as@virginia.edu', first_name = 'George', last_name = 'Gelnovatch' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'University of Virginia' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "George Gelnovatch", "title": "Head Coach", "email": "Vrp9as@virginia.edu"}, {"name": "Matt Chulis", "title": "Associate Head Coach", "email": "mrc5r@virginia.edu"}]'::jsonb WHERE school_name = 'University of Virginia';

-- ── Syracuse University ──────────────────────────────────────────
UPDATE public.users SET email = 'ismcinty@syr.edu', first_name = 'Ian', last_name = 'McIntyre' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Syracuse University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Ian McIntyre", "title": "Head Coach", "email": "ismcinty@syr.edu"}, {"name": "Jukka Masalin", "title": "Associate Head Coach", "email": "jmasalin@syr.edu"}, {"name": "Matty Evans", "title": "Assistant Coach", "email": "cevans21@syr.edu"}]'::jsonb WHERE school_name = 'Syracuse University';

-- ── Grand Canyon University ──────────────────────────────────────────
UPDATE public.users SET email = 'jamie.davies@gcu.edu', first_name = 'Jamie', last_name = 'Davies' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Grand Canyon University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Jamie Davies", "title": "Head Coach", "email": "jamie.davies@gcu.edu"}, {"name": "Craig McCall", "title": "Assistant Coach", "email": "craig.mccall@gcu.edu"}, {"name": "Michael Garrihy", "title": "Assistant Coach", "email": "michael.garrihy@gcu.edu"}]'::jsonb WHERE school_name = 'Grand Canyon University';

-- ── Cal Poly San Luis Obispo ──────────────────────────────────────────
UPDATE public.users SET email = 'mensoccer@calpoly.edu', first_name = 'Oige', last_name = 'Kennedy' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Cal Poly San Luis Obispo' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Oige Kennedy", "title": "Men''s Soccer Head Coach", "email": "mensoccer@calpoly.edu"}, {"name": "Zach Watson", "title": "Assistant Coach", "email": "zwatso01@calpoly.edu"}, {"name": "Brandon Bautista", "title": "Assistant Coach", "email": "bbauti11@calpoly.edu"}]'::jsonb WHERE school_name = 'Cal Poly San Luis Obispo';

-- ── Nova Southeastern University ──────────────────────────────────────────
UPDATE public.users SET email = 'mmcarthu@nova.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Nova Southeastern University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Men''s Soccer Coach", "title": "mmcarthu@nova.edu", "email": "mmcarthu@nova.edu"}, {"name": "Assistant Men''s Soccer Coach", "title": "mperezba@nova.edu", "email": "mperezba@nova.edu"}]'::jsonb WHERE school_name = 'Nova Southeastern University';

-- ── Wheeling University ──────────────────────────────────────────
UPDATE public.users SET email = 'bregan@wheeling.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Wheeling University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Men''s Soccer Coach", "title": "", "email": "bregan@wheeling.edu"}, {"name": "Graduate Assistant Men''s Soccer Coach", "title": "", "email": "cmolinacuriel954@cardinal.wheeling.edu"}]'::jsonb WHERE school_name = 'Wheeling University';

-- ── Lynn University ──────────────────────────────────────────
UPDATE public.users SET email = 'jrootes@lynn.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Lynn University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Men''s Soccer Coach", "title": "(561) 237-7245(561) 237-7245", "email": "jrootes@lynn.edu"}, {"name": "Assistant Coach", "title": "(561) 237-7103(561) 237-7103", "email": "adesperito@lynn.edu"}]'::jsonb WHERE school_name = 'Lynn University';

-- ── Davis & Elkins College ──────────────────────────────────────────
UPDATE public.users SET email = 'lewinm@dewv.edu', first_name = 'Meir', last_name = 'Lewin' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Davis & Elkins College' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Meir Lewin", "title": "Head Men''s Soccer Coach", "email": "lewinm@dewv.edu"}, {"name": "Remy Tazifor", "title": "Assistant Men''s Soccer Coach", "email": "taziforr@dewv.edu"}, {"name": "Gadi  Vogel", "title": "Assistant Men''s Soccer Coach", "email": "vogelg@dewv.edu"}]'::jsonb WHERE school_name = 'Davis & Elkins College';

-- ── Williams College ──────────────────────────────────────────
UPDATE public.users SET email = 'ss40@williams.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Williams College' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Coach", "title": "413-597-2601413-597-2601", "email": "ss40@williams.edu"}, {"name": "Assistant Coach", "title": "413-597-4348413-597-4348", "email": "williamsmenssoccer@gmail.com"}]'::jsonb WHERE school_name = 'Williams College';

-- ── Amherst College ──────────────────────────────────────────
UPDATE public.users SET email = 'jserpone@amherst.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Amherst College' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Coach of Men''s Soccer / Director of Amherst LEADS", "title": "jserpone@amherst.edu", "email": "jserpone@amherst.edu"}, {"name": "Assistant Coach, Men''s Soccer", "title": "aortega@amherst.edu", "email": "aortega@amherst.edu"}]'::jsonb WHERE school_name = 'Amherst College';

-- ── Middlebury College ──────────────────────────────────────────
UPDATE public.users SET email = 'aelias@middlebury.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Middlebury College' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Men''s Soccer Coach", "title": "aelias@middlebury.edu", "email": "aelias@middlebury.edu"}, {"name": "Assistant Men''s Soccer Coach", "title": "tp@middlebury.edu", "email": "tp@middlebury.edu"}, {"name": "Assistant Men''s Soccer Coach", "title": "bpotter@middlebury.edu", "email": "bpotter@middlebury.edu"}, {"name": "Assistant Men''s Soccer Coach - Goalkeepers", "title": "lagazo@middlebury.edu", "email": "lagazo@middlebury.edu"}]'::jsonb WHERE school_name = 'Middlebury College';

-- ── Tufts University ──────────────────────────────────────────
UPDATE public.users SET email = 'menssoccer@tufts.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Tufts University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Coach", "title": "617-627-5152617-627-5152", "email": "menssoccer@tufts.edu"}, {"name": "Assistant Coach", "title": "", "email": "menssoccer@tufts.edu"}, {"name": "Assistant Coach", "title": "", "email": "menssoccer@tufts.edu"}, {"name": "Assistant Coach", "title": "", "email": "menssoccer@tufts.edu"}, {"name": "Assistant Coach", "title": "", "email": "menssoccer@tufts.edu"}]'::jsonb WHERE school_name = 'Tufts University';

-- ── Lindsey Wilson College ──────────────────────────────────────────
UPDATE public.users SET email = 'buthelezis@lindsey.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Lindsey Wilson College' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Coach", "title": "buthelezis@lindsey.edu", "email": "buthelezis@lindsey.edu"}]'::jsonb WHERE school_name = 'Lindsey Wilson College';

-- ── Benedictine University ──────────────────────────────────────────
UPDATE public.users SET email = 'spappas@ben.edu' WHERE id = (   SELECT user_id FROM coaches WHERE school_name = 'Benedictine University' LIMIT 1);
UPDATE coaches SET assistant_staff = '[{"name": "Head Coach", "title": "630-829-6165630-829-6165", "email": "spappas@ben.edu"}, {"name": "Assistant Coach", "title": "", "email": "akomperda@ben.edu"}]'::jsonb WHERE school_name = 'Benedictine University';
